# Site Settings
title: Software Brewery
description: A game development blog
author: Robert Piwowarek
github_username: robpiwowarek

# Build Settings
markdown: kramdown
highlighter: rouge

baseurl: "" 
url: "https://robpiwowarek.github.io"

# Pagination Settings
paginate: 5
paginate_path: "/page/:num/"

# Add this section to enable the plugin
plugins:
  - jekyll-paginate