# Site Settings
title: Code & Conquest
description: A blog about programming deep dives and gaming adventures.
author: Your Name
github_username: your-username

# Build Settings
markdown: kramdown
highlighter: rouge

# NOWE LINIE - Ustawienia ścieżek (URL)
# Zastąp 'my-blog-repo-name' nazwą swojego repozytorium
baseurl: "" 
url: "https://robpiwowarek.github.io"