# Site Settings
title: Software Brewery
description: A game development blog
author: Robert Piwowarek
github_username: robpiwowarek

# Build Settings
markdown: kramdown
highlighter: rouge

baseurl: "" 
url: "https://robpiwowarek.github.io"

# Pagination Settings
paginate: 3
paginate_path: "/page/:num/"

# Custom Collections
collections:
  gamejams:
    output: true

# Add this section to enable the plugin
plugins:
  - jekyll-paginate

include: ['_pages']